version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "81:81"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
            - ./api:/api

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
            - ./api:/api

        stdin_open: true
        tty: true
        command: >
                bash -c "
                cd /app &&
                chmod u+rw  /var/cache &&
                composer install &&
                composer update &&
                php-fpm"
        
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret123'
            MYSQL_USER: 'developer'
            MYSQL_PASSWORD: 'secret123'
            MYSQL_DATABASE: 'librarydb'
        volumes:
            - mysqldata:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql
        restart: unless-stopped
volumes:
    mysqldata: {}
